### PR TITLE
implement transform_to_chinese()

### PR DESCRIPTION
**Pull request by sbhola**

### CODE REVIEW

**Comment by sbhola** [comment]
@rhettdsouza13 @mahapsub @RekhaGo please review.

**Comment by rhettdsouza13** [comment]
How do the results look like? I see you're using the same implementation as @mahapsub's with a specific list? I think it should be good.

**Comment by sbhola** [comment]
> How do the results look like? I see you're using the same implementation as @mahapsub's with a specific list? I think it should be good.

Results are fine, just same as to_indian() one.

**Comment by sbhola** [comment]
@rhettdsouza13 @mahapsub @RekhaGo added run.py for console i/o. please review.
@mahapsub many recipes are throwing errors for internal parsing, please consider adding error handling for parsing steps in general.

**Comment by rhettdsouza13** [comment]
Merging Chinese and run.py files.

**Pull request merged**
